import type { IncomingMessage, ServerResponse } from "node:http";
import { randomBytes } from "node:crypto";
import { prisma } from "@commerceos/database";
import { createToken, hashPassword } from "./auth.js";
import { signup } from "./signup.js";
import { createPublicOrder } from "./public-checkout.js";
import { getRequestContext, requireTenant } from "./tenant.js";

const json = (res: ServerResponse, status: number, body: unknown) => { res.statusCode = status; res.setHeader("content-type", "application/json; charset=utf-8"); res.end(JSON.stringify(body)); };
const body = async (req: IncomingMessage) => { let raw = ""; for await (const chunk of req) raw += chunk; return raw ? JSON.parse(raw) : {}; };
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const orderNumber = () => `CO-${Date.now().toString(36).toUpperCase()}-${randomBytes(3).toString("hex").toUpperCase()}`;
const orderStatuses = ["PENDING", "CONFIRMED", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "REFUNDED"] as const;

export const handleRequest = async (req: IncomingMessage, res: ServerResponse) => {
  res.setHeader("access-control-allow-origin", process.env.WEB_ORIGIN ?? "http://localhost:3000");
  res.setHeader("access-control-allow-headers", "content-type, authorization");
  res.setHeader("access-control-allow-methods", "GET, POST, PATCH, OPTIONS");
  if (req.method === "OPTIONS") return json(res, 204, null);
  try {
    const url = new URL(req.url ?? "/", "http://localhost");
    if (url.pathname === "/health" && req.method === "GET") return json(res, 200, { name: "CommerceOS API", status: "ok" });
    if (url.pathname === "/ready" && req.method === "GET") { await prisma.$queryRaw`SELECT 1`; return json(res, 200, { status: "ready", database: "ok" }); }
    if (url.pathname === "/auth/signup" && req.method === "POST") return json(res, 201, await signup(await body(req)));
    if (url.pathname === "/auth/dev-login" && req.method === "POST") { const input = await body(req); const user = await prisma.user.findFirst({ where: { email: String(input.email ?? "").trim().toLowerCase(), tenantId: input.tenantId } }); if (!user || user.passwordHash !== hashPassword(String(input.password ?? ""))) return json(res, 401, { error: "invalid_credentials" }); return json(res, 200, { token: createToken({ userId: user.id, tenantId: user.tenantId, role: user.role }) }); }

    const publicStoreMatch = url.pathname.match(/^\/public\/stores\/([^/]+)\/([^/]+)$/);
    if (publicStoreMatch && req.method === "GET") {
      const tenantSlug = decodeURIComponent(publicStoreMatch[1]); const storeSlug = decodeURIComponent(publicStoreMatch[2]);
      const store = await prisma.store.findFirst({ where: { slug: storeSlug, tenant: { slug: tenantSlug } }, select: { id: true, name: true, slug: true, currency: true, tenant: { select: { slug: true } }, products: { where: { status: "ACTIVE" }, include: { variants: { select: { id: true, sku: true, price: true, stock: true } } }, orderBy: { createdAt: "desc" } } } });
      return store ? json(res, 200, store) : json(res, 404, { error: "store_not_found" });
    }
    const publicCheckoutMatch = url.pathname.match(/^\/public\/stores\/([^/]+)\/([^/]+)\/orders$/);
    if (publicCheckoutMatch && req.method === "POST") {
      const tenantSlug = decodeURIComponent(publicCheckoutMatch[1]); const storeSlug = decodeURIComponent(publicCheckoutMatch[2]);
      const created = await createPublicOrder(await body(req), tenantSlug, storeSlug);
      return json(res, 201, { orderNumber: created.orderNumber, total: created.total.toString(), currency: created.currency, paymentMethod: created.paymentMethod, status: created.status });
    }
    const publicOrderMatch = url.pathname.match(/^\/public\/stores\/([^/]+)\/([^/]+)\/orders\/([^/]+)$/);
    if (publicOrderMatch && req.method === "GET") {
      const tenantSlug = decodeURIComponent(publicOrderMatch[1]); const storeSlug = decodeURIComponent(publicOrderMatch[2]); const orderNo = decodeURIComponent(publicOrderMatch[3]); const email = (url.searchParams.get("email") ?? "").trim().toLowerCase();
      if (!email) return json(res, 400, { error: "email is required" });
      const order = await prisma.order.findFirst({ where: { orderNumber: orderNo, store: { slug: storeSlug, tenant: { slug: tenantSlug } }, customer: { email } }, select: { orderNumber: true, status: true, paymentStatus: true, paymentMethod: true, subtotal: true, total: true, currency: true, shippingName: true, shippingAddress: true, createdAt: true, items: { select: { name: true, quantity: true, unitPrice: true, total: true }, orderBy: { name: "asc" } } } });
      if (!order) return json(res, 404, { error: "order_not_found" });
      return json(res, 200, { ...order, subtotal: order.subtotal.toString(), total: order.total.toString(), createdAt: order.createdAt.toISOString(), items: order.items.map(item => ({ ...item, unitPrice: item.unitPrice.toString(), total: item.total.toString() })) });
    }

    const context = getRequestContext(req.headers); const tenantId = requireTenant(context);
    if (url.pathname === "/me" && req.method === "GET") { const user = await prisma.user.findFirst({ where: { id: context.auth!.userId, tenantId }, select: { id: true, email: true, name: true, role: true, tenant: { select: { id: true, name: true, slug: true } } } }); return user ? json(res, 200, user) : json(res, 404, { error: "user_not_found" }); }
    if (url.pathname === "/dashboard" && req.method === "GET") { const [stores, products, orders, customers, revenue] = await Promise.all([prisma.store.count({ where: { tenantId } }), prisma.product.count({ where: { store: { tenantId }, status: "ACTIVE" } }), prisma.order.count({ where: { tenantId } }), prisma.customer.count({ where: { tenantId } }), prisma.order.aggregate({ where: { tenantId, paymentStatus: "PAID" }, _sum: { total: true } })]); return json(res, 200, { stores, products, orders, customers, revenue: revenue._sum.total?.toString() ?? "0" }); }
    if (url.pathname === "/stores" && req.method === "GET") return json(res, 200, await prisma.store.findMany({ where: { tenantId }, orderBy: { createdAt: "desc" } }));
    if (url.pathname === "/stores" && req.method === "POST") { const input = await body(req); if (!input.name) return json(res, 400, { error: "name is required" }); const slug = slugify(input.slug ?? input.name); if (!slug) return json(res, 400, { error: "valid slug is required" }); return json(res, 201, await prisma.store.create({ data: { tenantId, name: input.name, slug, currency: input.currency ?? "PKR" } })); }
    if (url.pathname === "/products" && req.method === "GET") return json(res, 200, await prisma.product.findMany({ where: { store: { tenantId } }, include: { variants: true }, orderBy: { createdAt: "desc" } }));
    if (url.pathname === "/products" && req.method === "POST") { const input = await body(req); if (!input.storeId || !input.name || !input.variant?.sku || input.variant?.price == null) return json(res, 400, { error: "storeId, name and variant sku/price are required" }); const store = await prisma.store.findFirst({ where: { id: input.storeId, tenantId } }); if (!store) return json(res, 404, { error: "store_not_found" }); const slug = slugify(input.slug ?? input.name); if (!slug) return json(res, 400, { error: "valid slug is required" }); return json(res, 201, await prisma.product.create({ data: { storeId: store.id, name: input.name, slug, description: input.description, status: input.status ?? "DRAFT", variants: { create: { sku: input.variant.sku, price: input.variant.price, stock: input.variant.stock ?? 0 } } }, include: { variants: true } })); }
    if (url.pathname === "/customers" && req.method === "GET") { const customers = await prisma.customer.findMany({ where: { tenantId }, orderBy: { createdAt: "desc" } }); const result = await Promise.all(customers.map(async customer => { const stats = await prisma.order.aggregate({ where: { tenantId, customerId: customer.id }, _count: { _all: true }, _sum: { total: true } }); return { ...customer, orderCount: stats._count._all, totalSpend: stats._sum.total?.toString() ?? "0" }; })); return json(res, 200, result); }
    const customerMatch = url.pathname.match(/^\/customers\/([^/]+)$/);
    if (customerMatch && req.method === "GET") { const customer = await prisma.customer.findFirst({ where: { id: customerMatch[1], tenantId }, include: { orders: { orderBy: { createdAt: "desc" }, include: { store: true, items: true } } } }); if (!customer) return json(res, 404, { error: "customer_not_found" }); const totalSpend = customer.orders.reduce((sum, order) => sum + Number(order.total), 0); return json(res, 200, { ...customer, orderCount: customer.orders.length, totalSpend: totalSpend.toFixed(2) }); }
    if (url.pathname === "/customers" && req.method === "POST") { const input = await body(req); const email = input.email ? String(input.email).trim().toLowerCase() : null; const phone = input.phone ? String(input.phone).trim() : null; if (!email && !phone) return json(res, 400, { error: "email or phone is required" }); const existing = await prisma.customer.findFirst({ where: { tenantId, OR: [...(email ? [{ email }] : []), ...(phone ? [{ phone }] : [])] } }); if (existing) return json(res, 200, existing); return json(res, 201, await prisma.customer.create({ data: { tenantId, email, phone, firstName: input.firstName, lastName: input.lastName } })); }
    if (url.pathname === "/orders" && req.method === "GET") return json(res, 200, await prisma.order.findMany({ where: { tenantId }, include: { customer: true, store: true, items: true }, orderBy: { createdAt: "desc" }, take: 100 }));
    const orderStatusMatch = url.pathname.match(/^\/orders\/([^/]+)\/status$/);
    if (orderStatusMatch && req.method === "PATCH") { const input = await body(req); const status = String(input.status ?? ""); if (!orderStatuses.includes(status as typeof orderStatuses[number])) return json(res, 400, { error: "invalid_order_status" }); const order = await prisma.order.findFirst({ where: { id: orderStatusMatch[1], tenantId } }); if (!order) return json(res, 404, { error: "order_not_found" }); const updated = await prisma.order.update({ where: { id: order.id }, data: { status: status as typeof order.status } }); return json(res, 200, { id: updated.id, orderNumber: updated.orderNumber, status: updated.status }); }
    if (url.pathname === "/orders" && req.method === "POST") {
      const input = await body(req); if (!input.storeId || !Array.isArray(input.items) || input.items.length === 0) return json(res, 400, { error: "storeId and at least one item are required" });
      const store = await prisma.store.findFirst({ where: { id: input.storeId, tenantId } }); if (!store) return json(res, 404, { error: "store_not_found" });
      const paymentMethod = input.paymentMethod ?? "COD"; if (!["COD", "MANUAL_BANK", "CARD", "WALLET"].includes(paymentMethod)) return json(res, 400, { error: "invalid_payment_method" });
      const shippingName = input.shippingName ?? input.customer?.name ?? null; const shippingPhone = input.shippingPhone ?? input.customer?.phone ?? null; const shippingAddress = input.shippingAddress ?? input.customer?.address ?? null; if (!shippingName || !shippingPhone || !shippingAddress) return json(res, 400, { error: "shipping name, phone and address are required" });
      const created = await prisma.$transaction(async tx => { let customerId: string | undefined; const email = input.customer?.email ? String(input.customer.email).trim().toLowerCase() : null; const phone = input.customer?.phone ? String(input.customer.phone).trim() : null; if (input.customerId) { const customer = await tx.customer.findFirst({ where: { id: input.customerId, tenantId } }); if (!customer) throw new Error("CUSTOMER_NOT_FOUND"); customerId = customer.id; } else if (email || phone) { const customer = await tx.customer.findFirst({ where: { tenantId, OR: [...(email ? [{ email }] : []), ...(phone ? [{ phone }] : [])] } }); if (customer) customerId = customer.id; else customerId = (await tx.customer.create({ data: { tenantId, email, phone, firstName: input.customer?.firstName, lastName: input.customer?.lastName } })).id; }
        const orderItems: { productId: string; variantId: string; name: string; quantity: number; unitPrice: number; total: number }[] = []; let subtotal = 0;
        for (const rawItem of input.items) { const quantity = Number(rawItem.quantity); if (!Number.isInteger(quantity) || quantity <= 0) throw new Error("INVALID_QUANTITY"); const variant = await tx.productVariant.findFirst({ where: { id: rawItem.variantId }, include: { product: { include: { store: true } } } }); if (!variant || variant.product.store.tenantId !== tenantId || variant.product.storeId !== store.id) throw new Error("ITEM_NOT_FOUND"); const price = Number(variant.price); const total = price * quantity; const updated = await tx.productVariant.updateMany({ where: { id: variant.id, stock: { gte: quantity } }, data: { stock: { decrement: quantity } } }); if (updated.count !== 1) throw new Error("INSUFFICIENT_STOCK"); orderItems.push({ productId: variant.productId, variantId: variant.id, name: variant.product.name, quantity, unitPrice: price, total }); subtotal += total; }
        return tx.order.create({ data: { tenantId, storeId: store.id, customerId, orderNumber: orderNumber(), status: input.status ?? "CONFIRMED", paymentStatus: input.paymentStatus ?? "PENDING", paymentMethod, subtotal, total: subtotal, currency: store.currency, shippingName, shippingPhone, shippingAddress, items: { create: orderItems } }, include: { customer: true, store: true, items: true } });
      }); return json(res, 201, { orderNumber: created.orderNumber, total: created.total.toString(), currency: created.currency, paymentMethod: created.paymentMethod, status: created.status });
    }
    return json(res, 404, { error: "not_found" });
  } catch (error) { if (error instanceof Error && error.message === "UNAUTHORIZED") return json(res, 401, { error: "unauthorized" }); if (error instanceof Error && error.message === "CUSTOMER_NOT_FOUND") return json(res, 404, { error: "customer_not_found" }); if (error instanceof Error && error.message === "INVALID_QUANTITY") return json(res, 400, { error: "quantity must be a positive integer" }); if (error instanceof Error && error.message === "ITEM_NOT_FOUND") return json(res, 404, { error: "order_item_not_found" }); if (error instanceof Error && error.message === "INSUFFICIENT_STOCK") return json(res, 409, { error: "insufficient_stock" }); if (error instanceof Error && error.message === "ITEMS_REQUIRED") return json(res, 400, { error: "at least one item is required" }); if (error instanceof Error && error.message === "SHIPPING_REQUIRED") return json(res, 400, { error: "email, shipping name, phone and address are required" }); if (error instanceof Error && error.message === "STORE_NOT_FOUND") return json(res, 404, { error: "store_not_found" }); if (error instanceof SyntaxError) return json(res, 400, { error: "invalid_json" }); console.error(error); return json(res, 500, { error: "internal_server_error" }); }
};
