"use client";

import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";

type Store = { id: string; name: string; slug: string; currency: string; products: Product[] };
type Product = { id: string; name: string; slug: string; description?: string | null; status: string; variants: { id: string; sku: string; price: string | number; stock: number }[] };
type CartItem = { product: Product; variantId: string; quantity: number };
type Confirmation = { orderNumber: string; total: string | number; currency: string; paymentMethod: string };

export default function StorefrontPage() {
  const [store, setStore] = useState<Store | null>(null); const [cart, setCart] = useState<CartItem[]>([]); const [checkoutOpen, setCheckoutOpen] = useState(false); const [confirmation, setConfirmation] = useState<Confirmation | null>(null); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState(""); const [paymentMethod, setPaymentMethod] = useState("COD"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void (async () => { try { const stores = await api<{ slug: string }[]>("/stores"); const slug = stores[0]?.slug; if (!slug) { setMessage("No store configured yet."); return; } setStore(await api<Store>(`/public/stores/${encodeURIComponent(slug)}`)); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load storefront"); } })(); }, []);
  const products = store?.products ?? []; const currency = store?.currency ?? "PKR"; const total = useMemo(() => cart.reduce((sum, item) => sum + Number(item.product.variants.find(v => v.id === item.variantId)?.price ?? 0) * item.quantity, 0), [cart]);
  const add = (product: Product) => { const variant = product.variants[0]; if (!variant || variant.stock <= 0) return; setCart(current => { const found = current.find(i => i.variantId === variant.id); return found ? current.map(i => i.variantId === variant.id ? { ...i, quantity: Math.min(i.quantity + 1, variant.stock) } : i) : [...current, { product, variantId: variant.id, quantity: 1 }]; }); setMessage(""); };
  const checkout = async (event: React.FormEvent) => { event.preventDefault(); if (!store || !email || !name || !phone || !address || cart.length === 0) return; setBusy(true); setMessage(""); try { const order = await api<Confirmation>("/orders", { method: "POST", body: JSON.stringify({ storeId: store.id, paymentMethod, customer: { email, name, phone, address }, shippingName: name, shippingPhone: phone, shippingAddress: address, items: cart.map(i => ({ variantId: i.variantId, quantity: i.quantity })) }) }); setCart([]); setCheckoutOpen(false); setConfirmation(order); setEmail(""); setName(""); setPhone(""); setAddress(""); } catch (e) { setMessage(e instanceof Error ? e.message : "Checkout failed"); } finally { setBusy(false); } };
  if (confirmation) return <main className="confirmation-page"><div className="confirmation-card"><span className="eyebrow">ORDER CONFIRMED</span><h1>Thank you for your order.</h1><p className="muted">Order <strong>#{confirmation.orderNumber}</strong> has been received.</p><div className="confirmation-total"><span>Total</span><strong>{confirmation.currency} {Number(confirmation.total).toFixed(2)}</strong></div><div className="cod-note"><strong>{confirmation.paymentMethod === "COD" ? "Cash on Delivery" : confirmation.paymentMethod}</strong><span>{confirmation.paymentMethod === "COD" ? "Payment is due when your order is delivered." : "Your selected payment method is recorded on the order."}</span></div><button className="checkout-button" onClick={() => setConfirmation(null)}>Continue shopping</button></div></main>;
  return <main className="storefront"><header className="store-header"><div><div className="store-brand">{store?.name ?? "CommerceOS Store"}</div><div className="muted">Shop online</div></div><button className="cart-button" onClick={() => setCheckoutOpen(true)} disabled={cart.length === 0}>Cart ({cart.reduce((n, i) => n + i.quantity, 0)}) · {currency} {total.toFixed(2)}</button></header><section className="store-hero"><span className="eyebrow">MODERN COMMERCE</span><h1>{store?.name ?? "Your storefront"}</h1><p>Discover products and check out through CommerceOS.</p></section><section className="product-grid">{products.length === 0 ? <div className="empty-state">No active products are available yet.</div> : products.map(product => { const variant = product.variants[0]; return <article className="product-card" key={product.id}><div className="product-art">{product.name.slice(0, 1).toUpperCase()}</div><div className="product-info"><div><h2>{product.name}</h2><p>{product.description || "Quality product from our store."}</p></div><div className="product-buy"><strong>{currency} {variant?.price ?? "0"}</strong><button onClick={() => add(product)} disabled={!variant || variant.stock <= 0}>{variant?.stock ? "Add to cart" : "Out of stock"}</button></div></div></article>; })}</section>{message && <div className="store-message">{message}</div>}{checkoutOpen && <div className="modal-backdrop"><form className="checkout-card" onSubmit={checkout}><div className="detail-header"><div><h2>Checkout</h2><div className="muted">{cart.reduce((n, i) => n + i.quantity, 0)} item(s) · {currency} {total.toFixed(2)}</div></div><button type="button" className="secondary-button" onClick={() => setCheckoutOpen(false)}>Close</button></div><label>Full name<input required value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label><label>Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Phone<input required value={phone} onChange={e => setPhone(e.target.value)} placeholder="03xx xxxxxxx" /></label><label>Delivery address<input required value={address} onChange={e => setAddress(e.target.value)} placeholder="Street, area, city" /></label><div className="payment-choice"><strong>Payment method</strong><label className="radio-row"><input type="radio" checked={paymentMethod === "COD"} onChange={() => setPaymentMethod("COD")} /> Cash on Delivery</label><div className="muted small">Online payment methods can be enabled later.</div></div><div className="checkout-items">{cart.map(item => <div className="product-row" key={item.variantId}><span>{item.product.name} × {item.quantity}</span><strong>{currency} {(Number(item.product.variants.find(v => v.id === item.variantId)?.price ?? 0) * item.quantity).toFixed(2)}</strong></div>)}</div><button className="checkout-button" disabled={busy}>{busy ? "Placing order..." : "Place COD order"}</button></form></div>}</main>;
}
